on:
  issues:
    types: [opened, edited]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    name: Automatic Github Issue Labeller
    steps:
    - name: Label Step
      uses: larrylawl/Auto-Github-Issue-Labeller@v1.0
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        REPOSITORY: ${{github.repository}}
        DELTA: "20"
        CONFIDENCE: "2"
        FEATURE: "enhancement"
        BUG: "bug"
        DOCS: "documentation"

